//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptops.Service
{
    using System;
    using System.Collections.Generic;using PrismLaptopManager.Infrastructure;
    
    public partial class Laptop : ViewModelBase
    {
        private string _hostname;
    	public string Hostname 
    	{ 
    		get { return _hostname; } 
    		set
    		{
    			if (value != _hostname) {
    				_hostname = value;
    				 OnPropertyChanged("Hostname");
    			}
    		} 
    	}
    
        private string _primary_UID;
    	public string Primary_UID 
    	{ 
    		get { return _primary_UID; } 
    		set
    		{
    			if (value != _primary_UID) {
    				_primary_UID = value;
    				 OnPropertyChanged("Primary_UID");
    			}
    		} 
    	}
    
        private string _billed_UID;
    	public string Billed_UID 
    	{ 
    		get { return _billed_UID; } 
    		set
    		{
    			if (value != _billed_UID) {
    				_billed_UID = value;
    				 OnPropertyChanged("Billed_UID");
    			}
    		} 
    	}
    
        private Nullable<int> _last_connected;
    	public Nullable<int> Last_connected 
    	{ 
    		get { return _last_connected; } 
    		set
    		{
    			if (value != _last_connected) {
    				_last_connected = value;
    				 OnPropertyChanged("Last_connected");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _build_Date;
    	public Nullable<System.DateTime> Build_Date 
    	{ 
    		get { return _build_Date; } 
    		set
    		{
    			if (value != _build_Date) {
    				_build_Date = value;
    				 OnPropertyChanged("Build_Date");
    			}
    		} 
    	}
    
        private string _retired;
    	public string Retired 
    	{ 
    		get { return _retired; } 
    		set
    		{
    			if (value != _retired) {
    				_retired = value;
    				 OnPropertyChanged("Retired");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _retired_Date;
    	public Nullable<System.DateTime> Retired_Date 
    	{ 
    		get { return _retired_Date; } 
    		set
    		{
    			if (value != _retired_Date) {
    				_retired_Date = value;
    				 OnPropertyChanged("Retired_Date");
    			}
    		} 
    	}
    
        private string _oS;
    	public string OS 
    	{ 
    		get { return _oS; } 
    		set
    		{
    			if (value != _oS) {
    				_oS = value;
    				 OnPropertyChanged("OS");
    			}
    		} 
    	}
    
        private string _model;
    	public string Model 
    	{ 
    		get { return _model; } 
    		set
    		{
    			if (value != _model) {
    				_model = value;
    				 OnPropertyChanged("Model");
    			}
    		} 
    	}
    
        private string _mAC_Address;
    	public string MAC_Address 
    	{ 
    		get { return _mAC_Address; } 
    		set
    		{
    			if (value != _mAC_Address) {
    				_mAC_Address = value;
    				 OnPropertyChanged("MAC_Address");
    			}
    		} 
    	}
    
        private string _serial;
    	public string Serial 
    	{ 
    		get { return _serial; } 
    		set
    		{
    			if (value != _serial) {
    				_serial = value;
    				 OnPropertyChanged("Serial");
    			}
    		} 
    	}
    
        private string _duplicateSerial;
    	public string DuplicateSerial 
    	{ 
    		get { return _duplicateSerial; } 
    		set
    		{
    			if (value != _duplicateSerial) {
    				_duplicateSerial = value;
    				 OnPropertyChanged("DuplicateSerial");
    			}
    		} 
    	}
    
        private string _notes;
    	public string Notes 
    	{ 
    		get { return _notes; } 
    		set
    		{
    			if (value != _notes) {
    				_notes = value;
    				 OnPropertyChanged("Notes");
    			}
    		} 
    	}
    
        private string _friendly_OU;
    	public string Friendly_OU 
    	{ 
    		get { return _friendly_OU; } 
    		set
    		{
    			if (value != _friendly_OU) {
    				_friendly_OU = value;
    				 OnPropertyChanged("Friendly_OU");
    			}
    		} 
    	}
    
        private string _oU;
    	public string OU 
    	{ 
    		get { return _oU; } 
    		set
    		{
    			if (value != _oU) {
    				_oU = value;
    				 OnPropertyChanged("OU");
    			}
    		} 
    	}
    
        private Nullable<bool> _pool_Laptop;
    	public Nullable<bool> Pool_Laptop 
    	{ 
    		get { return _pool_Laptop; } 
    		set
    		{
    			if (value != _pool_Laptop) {
    				_pool_Laptop = value;
    				 OnPropertyChanged("Pool_Laptop");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _date_Added;
    	public Nullable<System.DateTime> Date_Added 
    	{ 
    		get { return _date_Added; } 
    		set
    		{
    			if (value != _date_Added) {
    				_date_Added = value;
    				 OnPropertyChanged("Date_Added");
    			}
    		} 
    	}
    
        private string _pL_Booking_CMP;
    	public string PL_Booking_CMP 
    	{ 
    		get { return _pL_Booking_CMP; } 
    		set
    		{
    			if (value != _pL_Booking_CMP) {
    				_pL_Booking_CMP = value;
    				 OnPropertyChanged("PL_Booking_CMP");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _pL_Booked_From;
    	public Nullable<System.DateTime> PL_Booked_From 
    	{ 
    		get { return _pL_Booked_From; } 
    		set
    		{
    			if (value != _pL_Booked_From) {
    				_pL_Booked_From = value;
    				 OnPropertyChanged("PL_Booked_From");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _pL_Booked_To;
    	public Nullable<System.DateTime> PL_Booked_To 
    	{ 
    		get { return _pL_Booked_To; } 
    		set
    		{
    			if (value != _pL_Booked_To) {
    				_pL_Booked_To = value;
    				 OnPropertyChanged("PL_Booked_To");
    			}
    		} 
    	}
    
        private string _pL_Checked_IN;
    	public string PL_Checked_IN 
    	{ 
    		get { return _pL_Checked_IN; } 
    		set
    		{
    			if (value != _pL_Checked_IN) {
    				_pL_Checked_IN = value;
    				 OnPropertyChanged("PL_Checked_IN");
    			}
    		} 
    	}
    
        private string _pL_Updated_By;
    	public string PL_Updated_By 
    	{ 
    		get { return _pL_Updated_By; } 
    		set
    		{
    			if (value != _pL_Updated_By) {
    				_pL_Updated_By = value;
    				 OnPropertyChanged("PL_Updated_By");
    			}
    		} 
    	}
    
        private string _pL_User_SOEID;
    	public string PL_User_SOEID 
    	{ 
    		get { return _pL_User_SOEID; } 
    		set
    		{
    			if (value != _pL_User_SOEID) {
    				_pL_User_SOEID = value;
    				 OnPropertyChanged("PL_User_SOEID");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _last_Updated;
    	public Nullable<System.DateTime> Last_Updated 
    	{ 
    		get { return _last_Updated; } 
    		set
    		{
    			if (value != _last_Updated) {
    				_last_Updated = value;
    				 OnPropertyChanged("Last_Updated");
    			}
    		} 
    	}
    
    }
}
