//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptops.Service
{
    using System;
    using System.Collections.Generic;using PrismLaptopManager.Infrastructure;
    
    public partial class Transaction : ViewModelBase
    {
        private int _iD;
    	public int ID 
    	{ 
    		get { return _iD; } 
    		set
    		{
    			if (value != _iD) {
    				_iD = value;
    				 OnPropertyChanged("ID");
    			}
    		} 
    	}
    
        private string _serial;
    	public string Serial 
    	{ 
    		get { return _serial; } 
    		set
    		{
    			if (value != _serial) {
    				_serial = value;
    				 OnPropertyChanged("Serial");
    			}
    		} 
    	}
    
        private string _hostname;
    	public string Hostname 
    	{ 
    		get { return _hostname; } 
    		set
    		{
    			if (value != _hostname) {
    				_hostname = value;
    				 OnPropertyChanged("Hostname");
    			}
    		} 
    	}
    
        private string _checkedOutTo;
    	public string CheckedOutTo 
    	{ 
    		get { return _checkedOutTo; } 
    		set
    		{
    			if (value != _checkedOutTo) {
    				_checkedOutTo = value;
    				 OnPropertyChanged("CheckedOutTo");
    			}
    		} 
    	}
    
        private string _status;
    	public string Status 
    	{ 
    		get { return _status; } 
    		set
    		{
    			if (value != _status) {
    				_status = value;
    				 OnPropertyChanged("Status");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _date_Time;
    	public Nullable<System.DateTime> Date_Time 
    	{ 
    		get { return _date_Time; } 
    		set
    		{
    			if (value != _date_Time) {
    				_date_Time = value;
    				 OnPropertyChanged("Date_Time");
    			}
    		} 
    	}
    
        private string _updated_By;
    	public string Updated_By 
    	{ 
    		get { return _updated_By; } 
    		set
    		{
    			if (value != _updated_By) {
    				_updated_By = value;
    				 OnPropertyChanged("Updated_By");
    			}
    		} 
    	}
    
    }
}
